#####################################################
#                  ArcaneTable Config               #
#####################################################

disenchant:
  # enable or disable the disenchant feature
  enabled: true
  # percentage of XP to return -1 to disable 100 to return all
  xp-percentage: 100
